# Generated by Django 3.0.7 on 2020-06-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absentelkom', '0002_tbl_acara_keterangan_acara'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_absen_ami',
            name='id_guru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='absentelkom.Tbl_guru'),
        ),
    ]
