# Generated by Django 3.0.7 on 2020-06-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absentelkom', '0003_tbl_absen_ami_id_guru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_jampel_end',
            name='id_jampel_end',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbl_jampel_start',
            name='id_jampel_start',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
